// объекты для аренды
export const propertiesForRent = [
  {
    id: 1,
    category: "flat",
    room: 1,
    img: "/img/flat1.png",
    price: 1000,
    address: "улица 1, дом 1",
    hot: true,
  },
  {
    id: 2,
    category: "house",
    room: 1,
    img: "/img/flat1.png",
    price: 1100,
    address: "улица 11, дом 11",
    hot: true,
  },
  {
    id: 3,
    category: "commerce",
    room: 1,
    img: "/img/flat1.png",
    price: 1200,
    address: "улица 12, дом 12",
    hot: true,
  },
  {
    id: 4,
    category: "flat",
    room: 1,
    img: "/img/flat1.png",
    price: 1300,
    address: "улица 2, дом 2",
    hot: false,
  },
  {
    id: 5,
    category: "house",
    room: 1,
    img: "/img/flat1.png",
    price: 1400,
    address: "улица 22, дом 22",
    hot: false,
  },
  {
    id: 6,
    category: "commerce",
    room: 2,
    img: "/img/flat1.png",
    price: 1500,
    address: "улица 21, дом 21",
    hot: false,
  },
  {
    id: 7,
    category: "flat",
    room: 2,
    img: "/img/flat1.png",
    price: 1600,
    address: "улица 3, дом 3",
    hot: false,
  },
  {
    id: 8,
    category: "house",
    room: 2,
    img: "/img/flat1.png",
    price: 1700,
    address: "улица 31, дом 31",
    hot: false,
  },
  {
    id: 9,
    category: "commerce",
    room: 2,
    img: "/img/flat1.png",
    price: 1800,
    address: "улица 32, дом 32",
    hot: false,
  },
  {
    id: 10,
    category: "flat",
    room: 2,
    img: "/img/flat1.png",
    price: 1900,
    address: "улица 4, дом 4",
    hot: false,
  },
  {
    id: 11,
    category: "house",
    room: 3,
    img: "/img/flat1.png",
    price: 2000,
    address: "улица 41, дом 41",
    hot: false,
  },
  {
    id: 12,
    category: "commerce",
    room: 3,
    img: "/img/flat1.png",
    price: 2100,
    address: "улица 42, дом 42",
    hot: false,
  },
  {
    id: 13,
    category: "flat",
    room: 3,
    img: "/img/flat1.png",
    price: 2200,
    address: "улица 5, дом 5",
    hot: false,
  },
  {
    id: 14,
    category: "house",
    room: 3,
    img: "/img/flat1.png",
    price: 2300,
    address: "улица 51, дом 51",
    hot: false,
  },
  {
    id: 15,
    category: "commerce",
    room: 3,
    img: "/img/flat1.png",
    price: 2400,
    address: "улица 52, дом 52",
    hot: false,
  },
];
// объекты для сдачи
export const propertiesForLease = [
    {
        id: 1,
        category: "flat",
        room: 1,
        img: "/img/flat1.png",
        price: 10,
        address: "улица 1, дом 1",
        hot: true,
      },
      {
        id: 2,
        category: "house",
        room: 1,
        img: "/img/flat1.png",
        price: 11,
        address: "улица 11, дом 11",
        hot: true,
      },
      {
        id: 3,
        category: "commerce",
        room: 1,
        img: "/img/flat1.png",
        price: 12,
        address: "улица 12, дом 12",
        hot: true,
      },
      {
        id: 4,
        category: "flat",
        room: 1,
        img: "/img/flat1.png",
        price: 13,
        address: "улица 2, дом 2",
        hot: false,
      },
      {
        id: 5,
        category: "house",
        room: 1,
        img: "/img/flat1.png",
        price: 14,
        address: "улица 22, дом 22",
        hot: false,
      },
      {
        id: 6,
        category: "commerce",
        room: 2,
        img: "/img/flat1.png",
        price: 15,
        address: "улица 21, дом 21",
        hot: false,
      },
      {
        id: 7,
        category: "flat",
        room: 2,
        img: "/img/flat1.png",
        price: 16,
        address: "улица 3, дом 3",
        hot: false,
      },
      {
        id: 8,
        category: "house",
        room: 2,
        img: "/img/flat1.png",
        price: 17,
        address: "улица 31, дом 31",
        hot: false,
      },
      {
        id: 9,
        category: "commerce",
        room: 2,
        img: "/img/flat1.png",
        price: 18,
        address: "улица 32, дом 32",
        hot: false,
      },
      {
        id: 10,
        category: "flat",
        room: 2,
        img: "/img/flat1.png",
        price: 19,
        address: "улица 4, дом 4",
        hot: false,
      },
      {
        id: 11,
        category: "house",
        room: 3,
        img: "/img/flat1.png",
        price: 20,
        address: "улица 41, дом 41",
        hot: false,
      },
      {
        id: 12,
        category: "commerce",
        room: 3,
        img: "/img/flat1.png",
        price: 21,
        address: "улица 42, дом 42",
        hot: false,
      },
      {
        id: 13,
        category: "flat",
        room: 3,
        img: "/img/flat1.png",
        price: 22,
        address: "улица 5, дом 5",
        hot: false,
      },
      {
        id: 14,
        category: "house",
        room: 3,
        img: "/img/flat1.png",
        price: 23,
        address: "улица 51, дом 51",
        hot: false,
      },
      {
        id: 15,
        category: "commerce",
        room: 3,
        img: "/img/flat1.png",
        price: 24,
        address: "улица 52, дом 52",
        hot: false,
      },
];
